### ISSUE TITLE
[MEET] 예외처리 클래스명

### ISSUE THREAD

**Issue by yejipractice** [almondiz/almondiz-server#23]
## 가능한 시간 ⏲️
깃

## 논의 내용 ❓
예외 처리를 기존에 있는 예외랑 분별할 목적으로(사실 필요성은 모르겠음) Custom Exception의 의미로 C를 붙여 작성했었는데, 
채련님은 안 붙이셨더라구요 그게 더 깔끔해보이기도 하고 흠 통일은 해야할 것 같아서.. 어떻게 생각하시나요? 붙이기 or 붙이지 않기 ?-?

**Comment by coderclcl** [comment]
저도 예제를 보고 C를 붙일까 고민했는데 딱히 구분할 필요는 없을 것 같아서 안붙이긴 했습니다! 통일이 필요하다면 안 붙이고 깔끔하게 가는 게 어떨까요 ?-?

**Comment by yejipractice** [comment]
안 붙이고 깔끔하게 가는 걸로 하겠습니다!
