### ISSUE TITLE
[BUG] UserController uri 수정 필요 

### ISSUE THREAD

**Issue by yejipractice** [almondiz/almondiz-server#29]
## 버그 설명 📓
> 팀원이 이해할 수 있도록 자세하게 구체적으로 작성합니다. 담당자도 함께 할당해주세요.
회원 정보 조회에서 조회 회원이 없을 때 "계정 존재 없음 에러 문구"가 뜨지 않고 바로 실패가 떴었음

원인은 아래 PathVarible이 설정되지 않았음

```
   @GetMapping(value="/user")
    @ApiOperation(value = "회원 정보 조회")
    public SingleResult<UserResponseDto> findUser(@PathVariable Long userId) {
        return responseService.getSingleResult(userService.getUser(userId));
    }
```

  ```
  @DeleteMapping(value="/user")
    @ApiOperation(value = "회원 탈퇴")
    public CommonResult deleteUser(@PathVariable Long userId) {
        userService.deleteUser(userId);
        return responseService.getSuccessResult();
    }
```

## 기대하는 결과 ☑️
> 구체적으로 어떤 결과가 나오게 수정해야 하는지 작성합니다.
아래처럼 pathvariable이 적용되도록 uri를 수정해야 합니다! 
- [ ] @GetMapping(value="/user/{userId}")
- [ ] @DeleteMapping(value="/user/{userId}")

## 참고자료 📖
>

**Comment by coderclcl** [comment]
고쳐야 하는 부분이 {userId} 를 붙여주면 되는거죠?? 
만약 해당 부분만 문제라면 #17 이슈 머지하면 모두 해결 될 것 같습니다!

**Comment by yejipractice** [comment]
#33  이슈랑 방안이 같으므로 이 이슈는 닫도록 하겠습니다!
