### ISSUE TITLE
[FEAT] profileBackgroundCode 추가 

### ISSUE THREAD

**Issue by coderclcl** [almondiz/almondiz-server#55]
## 설명 📓
> signup 할 때 profileId 뿐만 아니라 profileBackgroundCode 도 추가해야 함 
(현재 이모지와 백그라운드 두 개로 프로필을 생성)

## 체크사항 ☑️
> 이슈를 close하기 위해 필요한 조건들을 체크박스로 나열합니다.
- [ ] todo1
- [ ] todo2
- [ ] todo3

## 참고자료 ⁉️
> 이슈를 해결하기 위해 필요한 참고자료가 있다면 추가합니다.

## 관련 논의 🧑‍🤝‍🧑
> 이슈에 대한 논의가 있었다면 논의 내용을 간략하게 추가합니다.

**Comment by yejipractice** [comment]
#66 이슈, #70 브랜치에서 수정하였으므로 이슈 close
