### ISSUE TITLE
[BUG] 공용 swagger POST api 오류 해결 

### ISSUE THREAD

**Issue by coderclcl** [almondiz/almondiz-server#59]
## 버그 설명 📓
로컬 swagger에서 잘 동작하는 post 관련 api가 공용 swagger에서는 동작하지 않음 
@yejipractice 혹시 짐작되는 부분 있으면 알려주세요..! 

## 기대하는 결과 ☑️
> 구체적으로 어떤 결과가 나오게 수정해야 하는지 작성합니다.
- [ ] todo1
- [ ] todo2
- [ ] todo3

## 참고자료 📖
>

**Comment by yejipractice** [comment]
그거 userId (jwt) 아직 적용 안 시켜서 그런 거 아닌가요?-? @coderclcl

**Comment by coderclcl** [comment]
@yejipractice 아하 그 문제일 수 있겠네요..!! 그런데 왜 로컬에서는 잘 동작될까요..?? 서버에 JWT 관련 로직이 더 추가되어 있나요??

**Comment by yejipractice** [comment]
@coderclcl  하하 post랑 comment만 안되는군요 : - : 서버 다시 배포 해볼게요

**Comment by coderclcl** [comment]
@yejipractice 네넵 감사합니다!

**Comment by yejipractice** [comment]
@coderclcl  되네요? ㅎㅎ

**Comment by coderclcl** [comment]
@yejipractice 오...!! 빨리 잘 해결되어서 다행이에요!! 도와주셔서 감사합니다 :smiley::+1:
