### ISSUE TITLE
[FEAT] Post 리스트 api 수정 

### ISSUE THREAD

**Issue by coderclcl** [almondiz/almondiz-server#61]
## 설명 📓
> Post 리스트 api 수정 

## 체크사항 ☑️
> 추가해야할 것들 
- [ ] userProfileBackground, userProfileEmoji, profile img, alias, isFollowed 추가 (post와 comment의 작성자 user 둘 다)
- [ ] store 명칭 shop으로 변경 
- [ ] shopThumb 추가 
- [ ] 모든 createdAt unix로 변경 (comment와 post에 컬럼 없으면 생성)
- [ ] scrapCount 추가 
- [ ] commentCount 추가 
- [ ] comment에 likeCount 추가 

## 참고자료 ⁉️
> 이슈를 해결하기 위해 필요한 참고자료가 있다면 추가합니다.

## 관련 논의 🧑‍🤝‍🧑
> 이슈에 대한 논의가 있었다면 논의 내용을 간략하게 추가합니다.

**Comment by yejipractice** [comment]
단건처럼 dto 수정하기
